### ISSUE TITLE
lsl-viewer throws exception

### ISSUE THREAD

**Issue by ThomasZiegert** [bcimontreal/bci_workshop#21]
Hi,

when I try to setup the workshop files on a macbook pro, macos 10.13.5 I always get the following error, when starting the lsl-viewer:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/anaconda2/envs/py36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/anaconda2/envs/py36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "lsl-viewer.py", line 120, in update_plot
    max_samples=12)
  File "/anaconda2/envs/py36/lib/python3.6/site-packages/pylsl/pylsl.py", line 844, in pull_chunk
    handle_error(errcode)
  File "/anaconda2/envs/py36/lib/python3.6/site-packages/pylsl/pylsl.py", line 1134, in handle_error
    raise InternalError("an internal error has occurred.")
pylsl.pylsl.InternalError: an internal error has occurred.
```

Any help is highly appreciated.

Best regards,
Thomas

**Comment by ThomasZiegert** [comment]
What do you think @jdpigeon @hubertjb @syswsi @rcassani?

**Comment by jdpigeon** [comment]
Unfortunately, that error just indicates something went wrong with the compiled [liblsl](https://github.com/sccn/labstreaminglayer/tree/master/LSL/liblsl) C code and it's not very informative.

My suspicion is that this is related to the fact that this workshop code is a bit out of date compared to the new [Muse LSL](https://github.com/alexandrebarachant/muse-lsl/) library. We mean to refactor the workshop code to take advantage of Muse LSL more, but are still waiting to get the time.

I recommend installing Muse LSL and using it's CLI to create an LSL stream (`muselsl stream`) and view the data (`muselsl view`)

**Comment by ThomasZiegert** [comment]
Thanks, I'll try muselsl.
