### ISSUE TITLE
Windows 10 pygatt error 

### ISSUE THREAD

**Issue by Randulfe** [bcimontreal/bci_workshop#28]
I am getting the following error even after making the 0.25 second delay fix in the pygatt file : 
```
Traceback (most recent call last):
  File "muse-lsl.py", line 44, in <module>
    muse.connect()
  File "...\bci-workshop-master\python\muse\muse.py", line 44, in connect
    self.adapter.start()
  File "...\pygatt\backends\bgapi\bgapi.py", line 204, in start
    self._detect_device_port()
  File "...\pygatt\backends\bgapi\bgapi.py", line 147, in _detect_device_port
    raise BGAPIError("Unable to auto-detect BLED112 serial port")
pygatt.backends.bgapi.exceptions.BGAPIError: Unable to auto-detect BLED112 serial port
```
Any idea on how to solve this? Already tried resetting :(

**Comment by BRomans** [comment]
You need a BLED112 usb device. But after getting that it still can't find my Muse Headband
